"""create_initial_tables

Revision ID: 02241a26a59b
Revises: 498b3cc0bf49
Create Date: 2025-01-26 15:53:57.287110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02241a26a59b'
down_revision: Union[str, None] = '498b3cc0bf49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles_shared', sa.Column('shareTo', sa.String(), nullable=False))
    op.drop_column('articles_shared', 'shareOn')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles_shared', sa.Column('shareOn', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('articles_shared', 'shareTo')
    # ### end Alembic commands ###
