"""add_created_at_to_channels_subscribed

Revision ID: 2f8ee27629a6
Revises: d7b53b8b7b1f
Create Date: 2025-01-26 16:09:04.748465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f8ee27629a6'
down_revision: Union[str, None] = 'd7b53b8b7b1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles_saved', sa.Column('createdAt', sa.DateTime(), nullable=True))
    op.alter_column('articles_saved', 'userId',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('articles_saved', 'articleId',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('ix_articles_saved_id', table_name='articles_saved')
    op.drop_column('articles_saved', 'id')
    op.add_column('channels_subscribed', sa.Column('createdAt', sa.DateTime(), nullable=True))
    op.alter_column('channels_subscribed', 'userId',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('channels_subscribed', 'channelId',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('ix_channels_subscribed_id', table_name='channels_subscribed')
    op.drop_column('channels_subscribed', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels_subscribed', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_index('ix_channels_subscribed_id', 'channels_subscribed', ['id'], unique=False)
    op.alter_column('channels_subscribed', 'channelId',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('channels_subscribed', 'userId',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('channels_subscribed', 'createdAt')
    op.add_column('articles_saved', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_index('ix_articles_saved_id', 'articles_saved', ['id'], unique=False)
    op.alter_column('articles_saved', 'articleId',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('articles_saved', 'userId',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('articles_saved', 'createdAt')
    # ### end Alembic commands ###
