"""create_initial_tables

Revision ID: 498b3cc0bf49
Revises: a96bbf43e660
Create Date: 2025-01-26 15:43:13.429712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '498b3cc0bf49'
down_revision: Union[str, None] = 'a96bbf43e660'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles_shared',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('articleId', sa.Integer(), nullable=True),
    sa.Column('sharedAt', sa.DateTime(), nullable=True),
    sa.Column('sharedWith', sa.Integer(), nullable=True),
    sa.Column('shareOn', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['articleId'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['sharedWith'], ['users.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_articles_shared_id'), 'articles_shared', ['id'], unique=False)
    op.create_foreign_key(None, 'articles_saved', 'articles', ['articleId'], ['id'])
    op.drop_index('ix_press_reviews_name', table_name='press_reviews')
    op.create_index(op.f('ix_press_reviews_name'), 'press_reviews', ['name'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_press_reviews_name'), table_name='press_reviews')
    op.create_index('ix_press_reviews_name', 'press_reviews', ['name'], unique=True)
    op.drop_constraint(None, 'articles_saved', type_='foreignkey')
    op.drop_index(op.f('ix_articles_shared_id'), table_name='articles_shared')
    op.drop_table('articles_shared')
    # ### end Alembic commands ###
