"""create_initial_tables

Revision ID: d7b53b8b7b1f
Revises: 73544cfb589c
Create Date: 2025-01-26 16:02:06.646239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7b53b8b7b1f'
down_revision: Union[str, None] = '73544cfb589c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('radios_liked', sa.Column('createdAt', sa.DateTime(), nullable=True))
    op.alter_column('radios_liked', 'userId',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('radios_liked', 'radioId',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('ix_radios_liked_id', table_name='radios_liked')
    op.drop_column('radios_liked', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('radios_liked', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_index('ix_radios_liked_id', 'radios_liked', ['id'], unique=False)
    op.alter_column('radios_liked', 'radioId',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('radios_liked', 'userId',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('radios_liked', 'createdAt')
    # ### end Alembic commands ###
