"""create_initial_tables

Revision ID: f44e0750bb5f
Revises: 2f8ee27629a6
Create Date: 2025-01-28 13:22:43.008802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f44e0750bb5f'
down_revision: Union[str, None] = '2f8ee27629a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acces_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('additionalData', sa.String(), nullable=True),
    sa.Column('lastActivity', sa.DateTime(), nullable=True),
    sa.Column('createAt', sa.DateTime(), nullable=False),
    sa.Column('expireAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acces_keys_id'), 'acces_keys', ['id'], unique=False)
    op.create_index(op.f('ix_acces_keys_token'), 'acces_keys', ['token'], unique=True)
    op.drop_index('ix_sessions_id', table_name='sessions')
    op.drop_index('ix_sessions_sessionKey', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('idx_article_published', table_name='articles')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_article_published', 'articles', ['published'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('userId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sessionKey', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sessionData', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('userAgent', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('lastActivity', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('createAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('expireAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], name='sessions_userId_fkey'),
    sa.PrimaryKeyConstraint('id', name='sessions_pkey')
    )
    op.create_index('ix_sessions_sessionKey', 'sessions', ['sessionKey'], unique=True)
    op.create_index('ix_sessions_id', 'sessions', ['id'], unique=False)
    op.drop_index(op.f('ix_acces_keys_token'), table_name='acces_keys')
    op.drop_index(op.f('ix_acces_keys_id'), table_name='acces_keys')
    op.drop_table('acces_keys')
    # ### end Alembic commands ###
